"""add track playback metadata

Revision ID: 9882f562ceed
Revises: 1c5d0428f082
Create Date: 2026-05-16 16:48:15.098953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9882f562ceed'
down_revision: Union[str, Sequence[str], None] = '1c5d0428f082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('preview_url', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('playback_id', sa.String(length=255), nullable=True))
    op.add_column(
        'tracks',
        sa.Column(
            'is_playable',
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
    )
    op.add_column(
        'tracks',
        sa.Column('metadata_synced_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'tracks',
        sa.Column(
            'provider_metadata',
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                'postgresql',
            ),
            nullable=True,
        ),
    )
    op.alter_column('tracks', 'is_playable', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'provider_metadata')
    op.drop_column('tracks', 'metadata_synced_at')
    op.drop_column('tracks', 'is_playable')
    op.drop_column('tracks', 'playback_id')
    op.drop_column('tracks', 'preview_url')
    # ### end Alembic commands ###
