"""add provider tracks

Revision ID: f6d3b338bb76
Revises: 9882f562ceed
Create Date: 2026-05-18 14:27:22.700863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d3b338bb76'
down_revision: Union[str, Sequence[str], None] = '9882f562ceed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_track_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('artist_name', sa.String(length=240), nullable=True),
    sa.Column('album_name', sa.String(length=240), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('playback_id', sa.String(length=255), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('provider_url', sa.Text(), nullable=True),
    sa.Column('is_playable', sa.Boolean(), nullable=False),
    sa.Column('playback_source', sa.String(length=40), nullable=True),
    sa.Column('provider_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metadata_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_track_id', name='uq_provider_tracks_provider_track')
    )
    op.create_index(op.f('ix_provider_tracks_track_id'), 'provider_tracks', ['track_id'], unique=False)
    op.create_index('ix_provider_tracks_track_provider', 'provider_tracks', ['track_id', 'provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_tracks_track_provider', table_name='provider_tracks')
    op.drop_index(op.f('ix_provider_tracks_track_id'), table_name='provider_tracks')
    op.drop_table('provider_tracks')
    # ### end Alembic commands ###
